import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Admin One',
      email: 'admin1@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'BigBooks',
        logo: '/images/logo1.png',
        description: 'Best Seller',
        rating: 4.8,
        numReviews: 420,
      },
    },
    {
      name: 'Admin Two',
      email: 'admin2@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'HugeBooks',
        logo: '/images/logo2.png',
        description: 'Top Seller',
        rating: 4.6,
        numReviews: 360,
      },
    },
    {
      name: 'Admin Three',
      email: 'admin3@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
      isSeller: true,
      seller: {
        name: 'GiantBooks',
        logo: '/images/logo3.png',
        description: 'Best Seller',
        rating: 4.5,
        numReviews: 420,
      },
    },
    {
      name: 'User',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Never A Lovely So Real',
      category: 'Reality',
      image: '/images/p1.jpg',
      price: 15,
      countInStock: 10,
      author: 'Colin Asher',
      rating: 4.5,
      numReviews: 10,
      description: 'Nice book',
    },
    {
      name: 'Feast Your Eyes',
      category: 'Fiction',
      image: '/images/p2.jpg',
      price: 35,
      countInStock: 30,
      author: 'Myla Goldberg',
      rating: 4.0,
      numReviews: 9,
      description: 'Great book',
    },
    {
      name: 'Ghost Wall',
      category: 'Fiction',
      image: '/images/p3.jpg',
      price: 20,
      countInStock: 20,
      author: 'Sarah Moss',
      rating: 4.8,
      numReviews: 11,
      description: 'Amazing book',
    },
    {
      name: 'Crossing',
      category: 'Reality',
      image: '/images/p4.jpg',
      price: 650,
      countInStock: 15,
      author: 'Pajtim Statovci',
      rating: 4.5,
      numReviews: 14,
      description: 'Fantastic book',
    },
    {
      name: 'Say Nothing',
      category: 'Reality',
      image: '/images/p5.jpg',
      price: 25,
      countInStock: 5,
      author: 'Patrick Radden Keefe',
      rating: 4.5,
      numReviews: 10,
      description: 'Splendid book',
    },
    {
      name: 'Queenie',
      category: 'Fiction',
      image: '/images/p6.jpg',
      price: 40,
      countInStock: 12,
      author: 'Candice Carty-Williams',
      rating: 4.7,
      numReviews: 15,
      description: 'Life-changing book',
    },
    {
      name: 'We Cast A Shadow',
      category: 'Fiction',
      image: '/images/p7.jpg',
      price: 800,
      countInStock: 12,
      author: 'Maurice Carlos Ruffin',
      rating: 5.0,
      numReviews: 35,
      description: 'Out of this world book',
    },
    {
      name: 'Normal People',
      category: 'Reality',
      image: '/images/p8.jpg',
      price: 5,
      countInStock: 12,
      author: 'Sally Rooney',
      rating: 3.2,
      numReviews: 13,
      description: 'Just an ok book',
    },
  ],
};
export default data;
